// <auto-generated />
namespace Code9.net._2016.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MenuItem_adding_active_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuItem_adding_active_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201604220726028_MenuItem_adding_active_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
